name: GitHub Actions Check File
on: [push]
#  pull_request_review:
#    types: [submitted]
#    paths:
#      - '***.md'

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -lah
